#!/bin/bash
set -e
./index.js ../src/account/oneview-account-balance/oneview-account-balance.component.ts 
./index.js ../src/account/oneview-credit-card/oneview-credit-card.component.ts 
./index.js ../src/actions/accordion-panel/accordion-panel.component.ts 
./index.js ../src/actions/action/action.component.ts 
./index.js ../src/actions/in-out-bound-offers/in-out-bound-offers.component.ts 
./index.js ../src/actions/offer/offer.component.ts 
./index.js ../src/actions/offer-details/offer-details.component.ts 
./index.js ../src/actions/offer-details-popup/offer-details-popup.component.ts 
./index.js ../src/actions/offer-group/offer-group.component.ts 
./index.js ../src/agent/agent-action/agent-action.component.ts 
./index.js ../src/agent/agent-credit-card/agent-credit-card.component.ts 
./index.js ../src/agent/agent-offer/agent-offer.component.ts 
./index.js ../src/agent/agent-offer-details/agent-offer-details.component.ts 
./index.js ../src/billing/billing-download-failure/billing-download-failure.component.ts 
./index.js ../src/billing/billing-download-success/billing-download-success.component.ts 
./index.js ../src/billing/billing-header/billing-header.component.ts 
./index.js ../src/billing/billing-overlay-message/billing-overlay-message.component.ts 
./index.js ../src/billing/loading/loading.component.ts 
./index.js ../src/oneview-common/dialog/dialog.component.ts 
./index.js ../src/oneview-common/dialog/error/error.component.ts 
./index.js ../src/oneview-common/dialog/info-dialog/info-dialog.component.ts 
./index.js ../src/oneview-common/dialog/success/success.component.ts 
./index.js ../src/oneview-common/oneview-calendar/oneview-calendar.component.ts 
./index.js ../src/oneview-common/oneview-carousel/oneview-carousel.component.ts 
./index.js ../src/oneview-common/oneview-cc-call/oneview-cc-call.component.ts 
./index.js ../src/oneview-common/oneview-cc-input/oneview-cc-input.component.ts 
./index.js ../src/oneview-common/oneview-cc-swipe/oneview-cc-swipe.component.ts 
./index.js ../src/oneview-common/oneview-dial/oneview-dial.component.ts 
./index.js ../src/oneview-common/oneview-loading/oneview-loading.component.ts 
./index.js ../src/oneview-common/oneview-menu/oneview-menu.component.ts 
./index.js ../src/oneview-common/oneview-price-value/oneview-price-value.component.ts 
./index.js ../src/oneview-common/oneview-radio/oneview-radio.component.ts 
./index.js ../src/oneview-common/oneview-search/oneview-search.component.ts 
./index.js ../src/oneview-common/oneview-select/oneview-select.component.ts 
./index.js ../src/oneview-common/oneview-tabs/oneview-tabs.component.ts 
./index.js ../src/oneview-common/oneview-text-field/oneview-text-field.component.ts 
./index.js ../src/oneview-common/oneview-tooltip/oneview-tooltip.component.ts 
./index.js ../src/oneview-common/oneview-type-ahead/oneview-type-ahead.component.ts 
./index.js ../src/overview/account-balance/account-balance.component.ts 
./index.js ../src/overview/actions-offers/action-offers.component.ts 
./index.js ../src/overview/bill/bill.component.ts 
./index.js ../src/overview/delinquency-indicator/delinquency-indicator.component.ts 
./index.js ../src/overview/hup-dialog/hup-dialog.component.ts 
./index.js ../src/overview/hup-error/hup-error.component.ts 
./index.js ../src/overview/interaction-item/interaction-item.component.ts 
./index.js ../src/overview/interaction-list/interaction-list.component.ts 
./index.js ../src/overview/services/service-badge-internet/service-badge-internet.component.ts 
./index.js ../src/overview/services/service-badge-rhp/service-badge-rhp.component.ts 
./index.js ../src/overview/services/service-badge-shared/service-badge-shared.component.ts 
./index.js ../src/overview/services/service-badge-shm/service-badge-shm.component.ts 
./index.js ../src/overview/services/service-badge-tv/service-badge-tv.component.ts 
./index.js ../src/overview/services/service-badge-wireless/service-badge-wireless.component.ts 
./index.js ../src/overview/services/services.component.ts 
./index.js ../src/overview/share-everything/share-everything.component.ts 
./index.js ../src/overview/user-info-message/user-info-message.component.ts 
./index.js ../src/payment/app-credit-card/app-credit-card.component.ts 
./index.js ../src/payment/change-payment-method/change-payment-method.component.ts 
./index.js ../src/payment/confirmation/confirmation.component.ts 
./index.js ../src/payment/payment-config/payment-config.component.ts 
./index.js ../src/payment/payment-failure/payment-failure.component.ts 
./index.js ../src/payment/payment-record/payment-record.component.ts 
./index.js ../src/payment/review/review.component.ts 
./index.js ../src/profile/app-payment-information/app-payment-information.component.ts 
./index.js ../src/profile/billing/billing.component.ts 
./index.js ../src/profile/contact-information/contact-information.component.ts 
./index.js ../src/profile/dialogs/billing-error/billing-error.component.ts 
./index.js ../src/profile/dialogs/change-billing-type/change-billing-type.component.ts 
./index.js ../src/profile/dialogs/reset-password/reset-password.component.ts 
./index.js ../src/profile/dialogs/verify-address/verify-address.component.ts 
./index.js ../src/profile/profile-error.component.ts 
./index.js ../src/service/oneview-service-container/oneview-service-container.component.ts 
./index.js ../src/service/oneview-service-internet-box/oneview-service-internet.component.ts 
./index.js ../src/service/oneview-service-rhp-box/oneview-service-rhp.component.ts 
./index.js ../src/service/oneview-service-shm-box/oneview-service-shm.component.ts 
./index.js ../src/service/oneview-service-tv-box/oneview-service-tv.component.ts 
./index.js ../src/service/oneview-service-wireless-box/oneview-service-wireless.component.ts 
./index.js ../src/service/oneview-shared-phone-box/oneview-shared-phone-box.component.ts 
./index.js ../src/translate/app-translate/app-translate.component.ts 
